name: publish

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  build-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotNET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          7.x
          8.x
          9.x
          10.x
    - name: Build
      run: |
        dotnet pack -c Release -o out DH.NIoT/DH.NIoT.csproj
        dotnet pack -c Release -o out DH.NIoTSocket/DH.NIoTSocket.csproj
        dotnet pack -c Release -o out DH.NIoTSerial/DH.NIoTSerial.csproj
        dotnet pack -c Release -o out DH.NIoTDatabase/DH.NIoTDatabase.csproj
    - name: Publish
      run: |
        # dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/PeiKeSmart/index.json --api-key ${{ github.token }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nugetKey }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.chuangchu.net/v3/index.json --api-key ${{ secrets.mynugetKey }}